# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94fea7f50a00401361d00fbf85ce866b087d91a00ce6aceeed87b84de2fcee4a4aac5643aa47ac4cd4edf99603fe51727e26ebdf4774786f048d5d4bc0910e87

test:
  secret_key_base: a401b1d9135ee7c353b98ec27d76a722074085a6925918b56fea900c4489c10cfa8f8aada9f2dd4055306988bb5c4561153f5590675217a8b45c050e0c21d5c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
